# Generated by Django 5.1.1 on 2025-11-01 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='actionlog',
            new_name='audit_actio_verb_142a68_idx',
            old_name='audit_action_verb_idx',
        ),
        migrations.RenameIndex(
            model_name='actionlog',
            new_name='audit_actio_timesta_a63ebd_idx',
            old_name='audit_action_ts_idx',
        ),
    ]
