# Generated by Django 5.1.1 on 2025-11-03 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0005_playbook_mode_manual_filters'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='playbookfilter',
            new_name='playbooks_p_target_bd82b6_idx',
            old_name='playbookfilter_target_idx',
        ),
        migrations.RenameIndex(
            model_name='playbookfilter',
            new_name='playbooks_p_playboo_0b9d46_idx',
            old_name='playbookfilter_playbook_target_idx',
        ),
        migrations.RenameIndex(
            model_name='playbooktrigger',
            new_name='playbooks_p_event_28fe4a_idx',
            old_name='playbooktr_event_d70721_idx',
        ),
        migrations.RenameIndex(
            model_name='playbooktrigger',
            new_name='playbooks_p_playboo_ea1958_idx',
            old_name='playbooktr_playboo_2066a2_idx',
        ),
    ]
