# Generated by Django 5.1.1 on 2026-04-11 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0008_executionstepresult'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='executionstepresult',
            new_name='playbooks_e_executi_84a5e1_idx',
            old_name='playbooks_e_executi_6b2d94_idx',
        ),
        migrations.RenameIndex(
            model_name='executionstepresult',
            new_name='playbooks_e_executi_c41cc3_idx',
            old_name='playbooks_e_executi_8be7f1_idx',
        ),
        migrations.RenameIndex(
            model_name='executionstepresult',
            new_name='playbooks_e_status_f96444_idx',
            old_name='playbooks_e_status_3af7dd_idx',
        ),
    ]
