# Generated by Django 5.1.1 on 2026-04-11 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSecretRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('provider', models.CharField(choices=[('env', 'Environment Variable')], default='env', max_length=32)),
                ('reference', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('action_name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='POST', max_length=8)),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('secret_ref', 'Secret Ref')], default='none', max_length=32)),
                ('request_template', models.JSONField(blank=True, default=dict)),
                ('expected_params', models.JSONField(blank=True, default=list)),
                ('response_mapping', models.JSONField(blank=True, default=dict)),
                ('post_response_actions', models.JSONField(blank=True, default=list)),
                ('timeout_seconds', models.PositiveIntegerField(default=15)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secret_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integrations', to='integrations.integrationsecretref')),
            ],
            options={
                'ordering': ['action_name'],
            },
        ),
    ]
