# Generated by Django 5.1.1 on 2026-04-12 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationsecretref',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='integrationsecretref',
            name='reference',
        ),
        migrations.AddField(
            model_name='integrationsecretref',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_integration_secret_refs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='integrationsecretref',
            name='rotated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationsecretref',
            name='rotated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotated_integration_secret_refs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='integrationsecretref',
            name='secret_value_encrypted',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
