# Generated by Django 5.1.1 on 2026-04-12 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_remove_integrationsecretref_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationdefinition',
            name='post_response_actions',
        ),
    ]
