# Generated by Django 5.1.1 on 2026-04-12 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_remove_integrationdefinition_post_response_actions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationdefinition',
            options={'ordering': ['action_name'], 'verbose_name': 'Conector HTTP', 'verbose_name_plural': 'Conectores HTTP'},
        ),
        migrations.AlterModelOptions(
            name='integrationsecretref',
            options={'ordering': ['name'], 'verbose_name': 'Secret do conector HTTP', 'verbose_name_plural': 'Secrets dos conectores HTTP'},
        ),
        migrations.AlterField(
            model_name='integrationdefinition',
            name='secret_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='http_connectors', to='integrations.integrationsecretref'),
        ),
        migrations.AlterField(
            model_name='integrationsecretref',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_http_connector_secrets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='integrationsecretref',
            name='rotated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotated_http_connector_secrets', to=settings.AUTH_USER_MODEL),
        ),
    ]
