# Generated by Django 5.1.1 on 2026-04-12 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_alter_integrationdefinition_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationdefinition',
            name='response_mapping',
        ),
    ]
