from django.urls import path

from . import views
from .views import CustomLoginView, CustomLogoutView

app_name = "webui"

urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    path("", views.DashboardView.as_view(), name="dashboard"),
    path("automation/", views.AutomationOverviewView.as_view(), name="automation_overview"),
    path("incidents/", views.IncidentListView.as_view(), name="incident_list"),
    path("artifacts/", views.artifact_directory, name="artifact_directory"),
    path("artifacts/<int:artifact_id>/delete/", views.artifact_delete, name="artifact_delete"),
    path("incidents/<int:pk>/", views.IncidentDetailView.as_view(), name="incident_detail"),
    path("incidents/<int:pk>/partials/summary/", views.incident_summary_partial, name="incident_summary_partial"),
    path("incidents/<int:pk>/partials/lifecycle/", views.incident_lifecycle_partial, name="incident_lifecycle_partial"),
    path("incidents/<int:pk>/status/", views.incident_update_status, name="incident_update_status"),
    path("incidents/<int:pk>/assignee/", views.incident_update_assignee, name="incident_update_assignee"),
    path("incidents/<int:pk>/assignee/search/", views.incident_assignee_search, name="incident_assignee_search"),
    path("incidents/<int:pk>/partials/labels/", views.incident_labels_partial, name="incident_labels_partial"),
    path("incidents/<int:pk>/labels/add/", views.incident_label_add, name="incident_label_add"),
    path("incidents/<int:pk>/labels/remove/", views.incident_label_remove, name="incident_label_remove"),
    path("incidents/<int:pk>/labels/suggestions/", views.incident_label_suggestions, name="incident_label_suggestions"),
    path("incidents/<int:pk>/mitre/", views.incident_mitre_update, name="incident_mitre_update"),
    path("incidents/<int:pk>/partials/tasks/", views.incident_tasks_partial, name="incident_tasks_partial"),
    path("incidents/<int:pk>/tasks/", views.incident_task_create, name="incident_task_create"),
    path("incidents/<int:pk>/tasks/<int:task_id>/toggle/", views.incident_task_toggle, name="incident_task_toggle"),
    path("incidents/<int:pk>/tasks/<int:task_id>/update/", views.incident_task_update, name="incident_task_update"),
    path("incidents/<int:pk>/tasks/<int:task_id>/delete/", views.incident_task_delete, name="incident_task_delete"),
    path("incidents/<int:pk>/partials/artifacts/", views.incident_artifacts_partial, name="incident_artifacts_partial"),
    path("incidents/<int:pk>/artifacts/upload/", views.incident_artifact_upload, name="incident_artifact_upload"),
    path("incidents/<int:pk>/artifacts/link/", views.incident_artifact_link, name="incident_artifact_link"),
    path("incidents/<int:pk>/artifacts/<int:artifact_id>/edit/", views.incident_artifact_edit, name="incident_artifact_edit"),
    path("incidents/<int:pk>/artifacts/<int:artifact_id>/update/", views.incident_artifact_update, name="incident_artifact_update"),
    path("incidents/<int:pk>/artifacts/<int:artifact_id>/action/", views.incident_artifact_action, name="incident_artifact_action"),
    path("incidents/<int:pk>/artifacts/<int:artifact_id>/playbooks/<int:playbook_id>/run/", views.incident_artifact_run_playbook, name="incident_artifact_run_playbook"),
    path("incidents/<int:pk>/export/pdf/", views.incident_export_pdf, name="incident_export_pdf"),
    path("incidents/<int:pk>/lifecycle/", views.incident_lifecycle_update, name="incident_lifecycle_update"),
    path("incidents/<int:pk>/partials/impact/", views.incident_impact_partial, name="incident_impact_partial"),
    path("incidents/<int:pk>/impact/", views.incident_impact_update, name="incident_impact_update"),
    path("incidents/<int:pk>/partials/escalation/", views.incident_escalation_partial, name="incident_escalation_partial"),
    path("incidents/<int:pk>/escalation/", views.incident_escalation_update, name="incident_escalation_update"),
    path("incidents/<int:pk>/partials/communications/", views.incident_communications_partial, name="incident_communications_partial"),
    path("incidents/<int:pk>/communications/", views.incident_communication_create, name="incident_communication_create"),
    path("incidents/<int:pk>/partials/relations/", views.incident_relations_partial, name="incident_relations_partial"),
    path("incidents/<int:pk>/relations/", views.incident_relation_create, name="incident_relation_create"),
    path("incidents/<int:pk>/relations/<int:relation_id>/delete/", views.incident_relation_delete, name="incident_relation_delete"),
    path("incidents/<int:pk>/partials/timeline/", views.incident_timeline_partial, name="incident_timeline_partial"),
    path("incidents/<int:pk>/timeline/", views.incident_timeline_add_note, name="incident_timeline_add_note"),
    path("incidents/<int:pk>/partials/playbooks/", views.incident_playbooks_partial, name="incident_playbooks_partial"),
    path("incidents/<int:pk>/playbooks/run/", views.incident_playbook_run, name="incident_playbook_run"),
    path("incidents/<int:pk>/playbooks/rerun/", views.incident_playbook_rerun, name="incident_playbook_rerun"),
    path("http-connectors/", views.HttpConnectorListView.as_view(), name="http_connector_list"),
    path("http-connectors/create/", views.HttpConnectorCreateView.as_view(), name="http_connector_create"),
    path("http-connectors/<int:pk>/edit/", views.HttpConnectorUpdateView.as_view(), name="http_connector_edit"),
    path("http-connectors/<int:pk>/test/", views.HttpConnectorTestView.as_view(), name="http_connector_test"),
    path("http-connector-secrets/", views.HttpConnectorSecretListView.as_view(), name="http_connector_secret_list"),
    path("http-connector-secrets/create/", views.HttpConnectorSecretCreateView.as_view(), name="http_connector_secret_create"),
    path("http-connector-secrets/<int:pk>/", views.HttpConnectorSecretDetailView.as_view(), name="http_connector_secret_detail"),
    path("http-connector-secrets/<int:pk>/edit/", views.HttpConnectorSecretUpdateView.as_view(), name="http_connector_secret_edit"),
    path("playbooks/", views.PlaybookListView.as_view(), name="playbook_list"),
    path("playbooks/create/", views.PlaybookCreateView.as_view(), name="playbook_create"),
    path("playbooks/<int:pk>/", views.PlaybookDetailView.as_view(), name="playbook_detail"),
    path("playbooks/<int:pk>/edit/", views.PlaybookUpdateView.as_view(), name="playbook_edit"),
    path("playbooks/<int:pk>/run/", views.PlaybookRunView.as_view(), name="playbook_run"),
]
