# Generated by Django 5.1.1 on 2025-11-01 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incident_enhancements'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artifact',
            unique_together=set(),
        ),
    ]
