# Generated by Django 5.1.1 on 2025-11-03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def link_existing_artifacts(apps, schema_editor):
    Artifact = apps.get_model("incidents", "Artifact")
    IncidentArtifact = apps.get_model("incidents", "IncidentArtifact")

    for artifact in Artifact.objects.all():
        incident_id = getattr(artifact, "incident_id", None)
        if not incident_id:
            continue
        IncidentArtifact.objects.get_or_create(
            incident_id=incident_id,
            artifact_id=artifact.id,
            defaults={"created_at": artifact.created_at},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0004_artifact_attributes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentArtifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_memberships",
                        to="incidents.artifact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifact_memberships",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("incident", "artifact")},
            },
        ),
        migrations.AddField(
            model_name="artifact",
            name="incidents",
            field=models.ManyToManyField(
                blank=True,
                related_name="artifacts",
                through="incidents.IncidentArtifact",
                to="incidents.incident",
            ),
        ),
        migrations.RunPython(link_existing_artifacts, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="artifact",
            name="incident",
        ),
    ]

