# Generated by Django 5.1.1 on 2026-04-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0009_customfielddefinition_internal_id_autoincrement"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="classification",
            field=models.CharField(
                choices=[
                    ("UNDETERMINED", "Undetermined"),
                    ("TRUE_POSITIVE", "True Positive"),
                    ("BENIGN_POSITIVE", "Benign Positive"),
                    ("FALSE_POSITIVE", "False Positive"),
                ],
                default="UNDETERMINED",
                max_length=24,
            ),
        ),
    ]
