# Generated by Django 5.1.1 on 2026-04-13 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0010_incident_classification"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="secondary_assignees",
            field=models.ManyToManyField(
                blank=True,
                related_name="incidents_escalated_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
